openapi: 3.0.3
info:
  title: Task Manager API
  description: API para la gestión de tareas del curso Diseño de APIs REST
  contact:
    name: Equipo del curso
    email: soporte@taskmanager.dev
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/fausti/LAB1/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://api.taskmanager.dev/v1
  description: Servidor de desarrollo
- url: https://staging.api.taskmanager.dev/v1
  description: Servidor de staging
tags:
  - name: Tasks
    description: Operaciones relacionadas con la gestión de tareas

# (2) Seguridad global: satisface "security-defined"
security:
  - bearerAuth: []

paths:
  /tasks:
    get:
      # (3) operationId requerido por el linter
      operationId: listTasks
      tags:
        - Tasks
      summary: Obtener todas las tareas
      description: Devuelve una lista de tareas registradas
      responses:
        '200':

          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'    
              examples:
                ejemplo:
                  value:
                    - id: "1"
                      title: "Mock desde OpenAPI"
                      status: "todo"
                    - id: "2"
                      title: "Preparar práctica de OpenAPI"
                      status: "in_progress"                        
        # (4) Al menos una 4xx
        '400':
          description: Petición inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      # (3) operationId requerido por el linter
      operationId: createTask
      tags:
        - Tasks
      summary: Crear una nueva tarea
      description: Crea una nueva tarea a partir de los datos enviados
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  id: { type: string, example: "1" }
                  title: { type: string, example: "Aprender OpenAPI" }
                  status: { type: string, example: "todo" }
              required: [title]
      responses:
        '201':
          description: Tarea creada correctamente
          content:
            application/json:
              examples:
                ejemplo:
                  value:
                    id: "2"
                    title: "Nueva tarea desde mock"
                    status: "todo"
                    createdAt: "2025-01-01T10:00:00Z"                
        # (4) Al menos una 4xx
        '400':
          description: Datos de entrada inválidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  # (1) Definición de esquema de seguridad
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      required:
        - title
        - status
      properties:
        id:
          type: string
          example: "64ab32cd9f0c1e12a45b78d9"
        title:
          type: string
          example: "Preparar práctica de OpenAPI"
        description:
          type: string
          example: "Definir modelos y esquemas en OpenAPI"
        status:
          type: string
          enum: [todo, in_progress, done]
          example: "todo"
        priority:
          type: string
          enum: [low, medium, high]
          example: "medium"
        dueDate:
          type: string
          format: date-time
          example: "2025-10-30T14:00:00Z"
        tags:                         
          type: array
          items:
            type: string
          example: ["work", "urgent"]
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: "Validation error"
        details:
          type: string
          example: "The field 'title' is required"

         
        